name: Python Hello World on Pull Request

on:
  pull_request:
    branches:
      - main  # Run the action on pull requests targeting the 'main' branch

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version

      - name: Run Hello World Script
        run: |
          echo "Hello, World from GitHub Actions!"
          python -c "print('Hello, World from Python!')"
